// Printable payment receipt (print → save as PDF).
'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Printer, Zap } from 'lucide-react';
import { api } from '@/lib/api';
import { money, fullDate } from '@/lib/format';
import { Button, Loading } from '@/components/ui';
import { useSession } from '@/lib/session';

interface Invoice { id: string; type: string; status: string; amount: string; transactionId: string | null; paidAt?: string | null; createdAt?: string }

export default function ReceiptPage() {
  const { id } = useParams<{ id: string }>();
  const session = useSession();
  const [order, setOrder] = useState<any>(null);

  useEffect(() => {
    api.get(`/orders/${id}`).then(setOrder).catch(console.error);
  }, [id]);

  if (!order) return <Loading />;

  const paid: Invoice[] = (order.invoices || []).filter((i: Invoice) => i.status === 'PAID');
  const totalPaid = paid.reduce((s, i) => s + Number(i.amount), 0);
  const due = Math.max(0, Number(order.totalAmount) - totalPaid);

  return (
    <div className="max-w-md">
      <div className="no-print mb-4 flex items-center justify-between">
        <Link href={`/dashboard/orders/${id}`} className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800">
          <ArrowLeft size={15} /> Back to order
        </Link>
        <Button onClick={() => window.print()}><Printer size={15} /> Print / Save PDF</Button>
      </div>

      {/* The receipt itself */}
      <div className="rounded-xl border-2 border-slate-900 bg-white p-6">
        <div className="flex items-center justify-between border-b-2 border-dashed border-slate-300 pb-4">
          <div className="flex items-center gap-2 font-bold">
            <Zap size={18} /> {session.tenant.businessName}
          </div>
          <span className="text-sm font-bold uppercase tracking-wide">Receipt</span>
        </div>

        <div className="space-y-4 py-4">
          <div className="flex justify-between text-sm">
            <div>
              <p className="text-xs font-bold uppercase tracking-wide text-slate-400">Order</p>
              <p className="font-bold">#{order.orderNumber}</p>
            </div>
            <div className="text-right">
              <p className="text-xs font-bold uppercase tracking-wide text-slate-400">Date</p>
              <p className="font-medium">{fullDate(order.createdAt)}</p>
            </div>
          </div>

          <div>
            <p className="text-xs font-bold uppercase tracking-wide text-slate-400">Billed to</p>
            <p className="mt-1 font-bold">{order.customerName}</p>
            <p className="text-sm">{order.phone}</p>
            <p className="text-sm">{order.address}, {order.district}</p>
          </div>

          <table className="w-full border-t-2 border-dashed border-slate-300 pt-2 text-sm">
            <tbody>
              {order.items.map((it: any) => (
                <tr key={it.id}>
                  <td className="pt-3">{it.product.name} × {it.quantity}</td>
                  <td className="pt-3 text-right font-medium">{money(it.subtotal)}</td>
                </tr>
              ))}
              {Number(order.deliveryFee) > 0 && (
                <tr className="text-slate-600">
                  <td className="pt-2">Delivery fee</td>
                  <td className="pt-2 text-right">{money(order.deliveryFee)}</td>
                </tr>
              )}
              {paid.map((i) => (
                <tr key={i.id} className="text-slate-600">
                  <td className="pt-2">
                    {i.type === 'ADVANCE' ? 'Advance received' : 'Payment received'}
                    {i.transactionId && <span className="ml-1 font-mono text-xs text-slate-400">({i.transactionId})</span>}
                  </td>
                  <td className="pt-2 text-right">−{money(i.amount)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="font-bold">
                <td className="pt-3">{due > 0 ? 'Balance due (COD)' : 'Balance due'}</td>
                <td className="border-t-2 border-slate-900 pt-3 text-right">{money(due)}</td>
              </tr>
            </tfoot>
          </table>

          <p className="border-t-2 border-dashed border-slate-300 pt-4 text-center text-xs text-slate-400">
            Thank you for shopping with {session.tenant.businessName}! · Generated by F-ComFlow
          </p>
        </div>
      </div>
    </div>
  );
}
